# -*- coding: utf-8 -*-
"""CW1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CxD99FEOSx7Yqp9qSkR9corD3n1HoLGh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

marvel = pd.read_csv("marvel-wikia-data.csv")

marvel.shape
marvel.dtypes

marvel.describe(include="all")

marvel = marvel.drop_duplicates()

marvel["Year"] = pd.to_numeric(marvel["Year"], errors="coerce")

marvel = marvel[marvel["APPEARANCES"].notna()]

categorical_cols = ["ALIGN", "EYE", "HAIR", "SEX", "ALIVE"]
for col in categorical_cols:
    marvel[col] = marvel[col].fillna(marvel[col].mode()[0])

marvel["Year"] = marvel["Year"].fillna(marvel["Year"].median())

marvel = marvel.reset_index(drop=True)

print(marvel.isna().sum())

marvel.head(5)

marvel.isna().sum()

marvel.duplicated().sum()

marvel.fillna({"APPEARANCES":marvel["APPEARANCES"].median()}, inplace=True)

marvel = marvel.drop_duplicates()

marvel["APPEARANCES"].describe()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))
plt.plot(marvel["Year"], marvel["APPEARANCES"])
plt.title("Appearances per Year")
plt.ylabel("Appearances")
plt.xlabel("Year")
plt.show()

plt.figure(figsize=(10,6))
plt.hist(marvel["APPEARANCES"].dropna(), bins=40, color="red", edgecolor="black")
plt.title("Distribution of Marvel Character Appearances")
plt.xlabel("Number of Appearances")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(10,6))
plt.scatter(marvel["Year"], marvel["APPEARANCES"], alpha=0.6, color="purple")
plt.title("Character Appearances vs. First Appearance Year")
plt.xlabel("Year of First Appearance")
plt.ylabel("Number of Appearances")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(marvel.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap of Numeric Features")
plt.show()

"""Portfolio Exercise 2:"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd

X = marvel[["ALIGN", "EYE", "HAIR", "SEX", "ALIVE", "Year"]]
y = marvel["APPEARANCES"]

X = pd.get_dummies(X, columns=["ALIGN", "EYE", "HAIR", "SEX", "ALIVE"], drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(n_estimators=200, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd

X = marvel[["ALIGN", "EYE", "HAIR", "SEX", "ALIVE", "Year"]]
y = marvel["APPEARANCES"]

X = pd.get_dummies(X, columns=["ALIGN", "EYE", "HAIR", "SEX", "ALIVE"], drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Linear Regression MSE:", mean_squared_error(y_test, y_pred))
print("Linear Regression R²:", r2_score(y_test, y_pred))

import numpy as np

rf_mse = mean_squared_error(y_test, y_pred)
rf_rmse = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test, y_pred)

lr_mse = mean_squared_error(y_test, y_pred_lr)
lr_rmse = np.sqrt(lr_mse)
lr_r2 = r2_score(y_test, y_pred_lr)

print("Random Forest MSE:", rf_mse)
print("Random Forest RMSE:", rf_rmse)
print("Random Forest R²:", rf_r2)

print("\nLinear Regression MSE:", lr_mse)
print("Linear Regression RMSE:", lr_rmse)
print("Linear Regression R²:", lr_r2)